#%RAML 0.8
title: Example API
version: v1
baseUri: http://localhost:3000/{version}
mediaType:  application/json
schemas:
 - User: !include shemas/users.json

/add:
   post:
      body:
        application/json:
          schema: User
